rust still broken on errors
$ time  rustc -VV
error: Option 'version' given more than once.

real  0m0.066s
user  0m0.033s
sys 0m0.027s

$ time RUST_BACKTRACE= rustc -VV
error: Option 'version' given more than once.

real  0m42.278s
user  0m41.973s
sys 0m0.233s

$ time RUST_BACKTRACE= rustc -Vv
rustc 1.6.0-dev (8ca0acc25 2015-10-28)
binary: rustc
commit-hash: 8ca0acc25adb00d29e52b015bded4b2872a1170c
commit-date: 2015-10-28
host: x86_64-unknown-linux-gnu
release: 1.6.0-dev

real  0m0.055s
user  0m0.033s
sys 0m0.020s

But here's the kicker:
stage1 still takes 0.6 sec and stage2 was taking the same amount until it
got fully compiled(maybe some libs got compiled in the meantime, but
also those libs that stage1 must not already have, since it still takes
0.6 sec for stage1)

https://github.com/rust-lang/rust/issues/29293